# Project information
site_name: Hackintosh the Thinkpad X1 Carbon 6th Gen
site_url: https://tylernguyen.github.io/x1c6-hackintosh
site_author: Tyler Nguyen

# Repository
repo_name: tylernguyen/x1c6-hackintosh
repo_url: https://github.com/tylernguyen/x1c6-hackintosh
edit_uri: ""

nav:
    - Home: index.md
    - Summary: Summary.md
    - Hardware: Hardware.md 
    - BIOS: BIOS.md
    - Getting Started: Getting-Started.md
    - Post Installation: Post-Installation.md
    - Issues: Issues.md
    - Technical Details:
      - config.plist: config.plist.md
      - Patches: Patches.md
      - ACPI Patch Snippets: https://github.com/5T33Z0/OC-Little-Translated
      - Keyboard Map: references/Keyboard.md
      - ALC285 Codec: references/ALC285.md
      - EC Queries: references/EC_queries.md
      - ASL Tutorial: https://acpica.org/sites/acpica/files/asl_tutorial_v20190625.pdf
      - ACPI Tips and Tricks: https://wiki.ubuntu.com/Kernel/Reference/ACPITricksAndTips
      - WhateverGreen Intel HD Manual: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md
      - UEFI Secure Boot: https://osy.gitbook.io/hac-mini-guide/details/secure-boot
      - HDA Fix: https://osy.gitbook.io/hac-mini-guide/details/hda-fix
      - Thunderbolt 3 (Part 1): https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix
      - Thunderbolt 3 (Part 2): https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix-part-2
      - Thunderbolt 3 (Part 3): https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix-part-3
      - MacbookPro14,1 ACPI: https://github.com/khronokernel/DarwinDumped/tree/master/MacBookPro/MacBookPro14%2C1
      - KabylakeOpenBoardPkg: https://github.com/tianocore/edk2-platforms/tree/master/Platform/Intel/KabylakeOpenBoardPkg

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: yellow
  features:
    - header.autohide
    - search.highlight
    - search.suggest
    - navigation.sections
    - navigation.tracking
  

plugins:
  - minify:
      minify_html: true
  - search

markdown_extensions:
  - admonition
  - footnotes

