# ANCHOR Project information
site_name: Hackintosh the Thinkpad X1 Carbon 2018/6th Gen
site_url: https://tylernguyen.github.io/x1c6-hackintosh
site_author: Tyler Nguyen
site_description: >-
   macOS on the Thinkpad X1 Carbon 2018/6th Generation, powered by OpenCore.

# ANCHOR Repository
repo_name: tylernguyen/x1c6-hackintosh
repo_url: https://github.com/tylernguyen/x1c6-hackintosh
edit_uri: "edit/main/docs/"

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git
    logo: material/laptop
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - announce.dismiss # NOTE Dismissable Announcement Banner
    - search.highlight # NOTE Highlight Matched Occurences after a Search
    - search.suggest
    - navigation.instant # NOTE Instant Loading on Internal Links with XMLHttpRequest (XHR)
    - navigation.top # NOTE Back-to-top button
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking # NOTE Update URL with Active Anchor
    - toc.follow # NOTE Anchor following in TOC
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tylernguyen
  # NOTE Hide "Made with Material for MkDocs"
  generator: false

extra_css:
  - stylesheets/extra.css

# ANCHOR PLugins
plugins:
  - git-revision-date
  - privacy
  - search
  - social
  - tags

# SECTION Extensions
markdown_extensions:
  # ANCHOR Python Markdown
  - admonition
  - attr_list # NOTE Grid, Annotations, Images, Buttons,
  - md_in_html # NOTE Grid, Annotations, Images
  - footnotes
  - meta # NOTE YAML Front Matter

 # ANCHOR Python Markdown Extensions
  - pymdownx.details # NOTE Admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences: # NOTE Admoniton, Annotations, MermaidJS
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
# !SECTION

# ANCHOR Page tree
nav:
    - Home: index.md
    - Hardware:
      - Parts Replacements: hardware/parts-replacements.md
      - Optimizing Hardware: hardware/optimizing-hardware.md
    - BIOS:
      - Settings for Vanilla BIOS: BIOS/settings-for-vanilla-BIOS.md
      - Modding the BIOS (optional): BIOS/modding-the-BIOS.md
      - Settings for Modded BIOS: BIOS/settings-for-modded-BIOS.md
    - Installing macOS: installing-macOS.md
    - Post Installation:
      - iCloud, iMessage, FaceTime: post-installation/iServices.md
      - Dual Booting: post-installation/dual-booting.md
      - Sleep: post-installation/sleep.md
      - Display: post-installation/display.md
      - Thunderbolt 3: post-installation/thunderbolt-3.md
      - Keyboard: post-installation/keyboard.md
      - Trackpad: post-installation/trackpad.md
    - Issues: issues.md
    - Technical Details:
        Internal:
          - config.plist: technical/config.plist.md
          - patches: technical/patches.md
          - Keyboard Queries: techical/keyboard-queries.md
          - ALC285 Codec: tecnical/ALC285.md
          - EC Queries: tecnical/EC-queries.md
        External:
          - ACPI Patch Snippets: https://github.com/5T33Z0/OC-Little-Translated
          - ASL Tutorial: https://acpica.org/sites/acpica/files/asl_tutorial_v20190625.pdf
          - ACPI Tips and Tricks: https://wiki.ubuntu.com/Kernel/Reference/ACPITricksAndTips
          - WhateverGreen Intel HD Manual: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md
          - UEFI Secure Boot Explaination: https://osy.gitbook.io/hac-mini-guide/details/secure-boot
          - Custom Secure Boot Keys and Signing OpenCore Binaries: https://github.com/profzei/Matebook-X-Pro-2018/wiki/Enable-BIOS-Secure-Boot-with-OpenCore
          - HDA Fix: https://osy.gitbook.io/hac-mini-guide/details/hda-fix
          - Thunderbolt 3 (Part 1): https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix
          - Thunderbolt 3 (Part 2): https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix-part-2
          - Thunderbolt 3 (Part 3): https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix-part-3
          - MacbookPro14,1 ACPI: https://github.com/khronokernel/DarwinDumped/tree/master/MacBookPro/MacBookPro14%2C1
          - KabylakeOpenBoardPkg: https://github.com/tianocore/edk2-platforms/tree/master/Platform/Intel/KabylakeOpenBoardPkg
          - CFG Unlock without BIOS Mod: https://www.reddit.com/r/hackintosh/comments/hz2rtm/cfg_lockunlocking_alternative_method/
