# Project information
site_name: Hackintosh the Thinkpad X1 Carbon 6th Gen
site_url: https://tylernguyen.github.io/x1c6-hackintosh
site_author: Tyler Nguyen

# Repository
repo_name: tylernguyen/x1c6-hackintosh
repo_url: https://github.com/tylernguyen/x1c6-hackintosh
edit_uri: ""

nav:
    - Home: index.md
    - Summary: Summary.md
    - Hardware: Hardware.md 
    - BIOS: BIOS.md
    - Getting Started: Getting-Started.md
    - Post Installation: Post-Installation.md
    - Issues: Issues.md
    - Technical Details:
      - config.plist: config.plist.md
      - Patches: Patches.md
      - WhateverGreen Intel HD Manual: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md
      - UEFI Secure Boot: https://osy.gitbook.io/hac-mini-guide/details/secure-boot
      - Thunderbolt 3 (Part 1): https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix
      - Thunderbolt 3 (Part 2): https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix-part-2
      - Thunderbolt 3 (Part 3): https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix-part-3

theme:
  name: material
  palette:
    primary: red
    accent: yellow
  features:
    - header.autohide
    - search.highlight
    - search.suggest

plugins:
  - minify:
      minify_html: true
  - search

markdown_extensions:
  - admonition

