# ANCHOR Project information
site_name: Hackintosh the Thinkpad X1 Carbon 2018/6th Gen
site_url: https://tylernguyen.github.io/x1c6-hackintosh
site_author: Tyler Nguyen
site_description: >-
   macOS on the Thinkpad X1 Carbon 2018/6th Generation, powered by OpenCore.

# ANCHOR Repository
repo_name: tylernguyen/x1c6-hackintosh
repo_url: https://github.com/tylernguyen/x1c6-hackintosh
edit_uri: "edit/main/docs/"

theme:
  name: material
  custom_dir: material
  icon:
    repo: fontawesome/brands/git
    logo: material/laptop
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - scheme: default
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - announce.dismiss # NOTE Dismissable Announcement Banner
    - content.tooltips
    - search.highlight # NOTE Highlight Matched Occurences after a Search
    - search.suggest
    - navigation.instant # NOTE Instant Loading on Internal Links with XMLHttpRequest (XHR)
    - navigation.top # NOTE Back-to-top button
    - navigation.tracking # NOTE Update URL with Active Anchor
    - navigation.sections
    - navigation.expand
    - toc.follow # NOTE Anchor following in TOC
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tylernguyen
  # NOTE Hide "Made with Material for MkDocs"
  generator: false

extra_css:
  - stylesheets/extra.css

# ANCHOR PLugins
plugins:
  - privacy
  - search
  - social
  - tags

# SECTION Extensions
markdown_extensions:
  # ANCHOR Python Markdown
  - admonition
  - attr_list # NOTE Grid, Annotations, Images, Buttons,
  - md_in_html # NOTE Grid, Annotations, Images
  - footnotes
  - meta # NOTE YAML Front Matter

 # ANCHOR Python Markdown Extensions
  - pymdownx.details # NOTE Admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - theme/.icons
  - pymdownx.superfences: # NOTE Admoniton, Annotations, MermaidJS
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
# !SECTION

# ANCHOR Page tree
nav:
    - Home: index.md
    - Hardware:
      - Parts Replacements: hardware/parts-replacements.md
      - Optimizing Hardware: hardware/optimizing-hardware.md
    - BIOS:
      - Settings for Vanilla BIOS: BIOS/settings-for-vanilla-BIOS.md
      - Modding the BIOS (optional): BIOS/modding-the-BIOS.md
      - Settings for Modded BIOS: BIOS/settings-for-modded-BIOS.md
    - Installing macOS: installing-macOS.md
    - Post Installation:
      - iCloud, iMessage, FaceTime: post-installation/iServices.md
      - Dual Booting: post-installation/dual-booting.md
      - Sleep: post-installation/sleep.md
      - Display: post-installation/display.md
      - Thunderbolt 3: post-installation/thunderbolt-3.md
      - Keyboard: post-installation/keyboard.md
      - Trackpad: post-installation/trackpad.md
    - Issues: issues.md
    - Technical Details: technical.md