name: tests
on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  ocvalidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: brokeyourbike/ocvalidate-action@v0.2
        with:
          opencore-version: '0.9.0'
          release: true
      - run: ocvalidate ./EFI/OC/config.plist | grep -q 'No issues found'